spring.application.name=projectCollab
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/projectcollab
spring.datasource.username=root
spring.datasource.password=ZagawMysql14
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
