spring.application.name=projectCollab
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/projectcollab
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=bXlhdCBoaXRpa2UgYXVua3Byb2plY3Rjb2xsYWJqd3RzZWNyZXRrZXkxMjM0NTY3ODkw
app.jwt.expiration=86400000

server.port=8080
